name: Manual Action
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      target:
        type: choice
        options:
          - world
          - galaxy
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}, World!"
      - run: echo ":-)"
